# Generated by Django 5.1.1 on 2024-10-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma1', models.CharField(max_length=100)),
                ('sintoma2', models.CharField(max_length=100)),
                ('sintoma3', models.CharField(max_length=100)),
                ('sintoma4', models.CharField(max_length=100)),
                ('sintoma5', models.CharField(max_length=100)),
            ],
        ),
    ]
