# Generated by Django 5.1.1 on 2024-10-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0002_sintomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomas',
            name='id_sintomas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diccionario.trastorno'),
        ),
    ]
