# Generated by Django 5.1.1 on 2024-10-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0003_sintomas_id_sintomas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sintomas',
            old_name='id_sintomas',
            new_name='trastorno',
        ),
    ]
