# Generated by Django 5.1.1 on 2024-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0004_rename_id_sintomas_sintomas_trastorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='trastorno',
            name='seleccionada',
            field=models.BooleanField(default=False),
        ),
    ]
