# Generated by Django 5.1.1 on 2024-12-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0004_rename_id_sintomas_sintomas_trastorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='trastorno',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trastorno',
            name='seleccionada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trastorno',
            name='contexto',
            field=models.CharField(max_length=500),
        ),
    ]
