# Generated by Django 5.1.1 on 2024-11-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0005_trastorno_seleccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='trastorno',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
